# Word2Vec Predictions

In [1]:
# import word2vec
import word2vec
import numpy as np

In [2]:
model = word2vec.load('../word2vec_output.bin')

In [3]:
model.vocab

array(['</s>', 'pablo_picasso', 'henri_matisse', ..., 'robert_morin',
       'alex_poruchnyk', 'jeanette_reinhardt'], dtype='<U78')

In [4]:
model.vectors.shape

(4913, 100)

In [5]:
model.vectors

array([[ 0.14333282,  0.15825513, -0.13715845, ...,  0.05456942,
         0.10955409,  0.00693387],
       [-0.12652822,  0.11665714, -0.00840823, ...,  0.06770407,
        -0.15354724,  0.02523407],
       [-0.03775577, -0.03028809, -0.01077749, ...,  0.01365833,
        -0.05170878,  0.02241292],
       ...,
       [-0.0553556 , -0.03825463,  0.01867852, ..., -0.11592786,
         0.17413543,  0.00783465],
       [-0.01820595, -0.09802575,  0.06219781, ..., -0.1619052 ,
         0.16925998,  0.03045541],
       [ 0.01497813, -0.05356211,  0.06185074, ..., -0.11414774,
         0.15682663,  0.00176715]])

In [6]:
model['paul_gauguin']

array([-0.08629142,  0.07500088,  0.11760277, -0.08249155, -0.06064167,
        0.07426202,  0.09430011,  0.03980861, -0.08868426, -0.07577797,
       -0.0789656 ,  0.04316986, -0.03742662,  0.0179255 , -0.02202932,
       -0.14584379, -0.0812774 ,  0.0817908 , -0.11009061, -0.07277608,
        0.02505444, -0.16708674,  0.09783117, -0.09566039,  0.20745072,
       -0.0382571 ,  0.03811841, -0.07231975, -0.25124985, -0.00223061,
       -0.15504658,  0.00175373, -0.0425612 ,  0.01211503, -0.21824302,
       -0.08570092, -0.11000088,  0.08192769,  0.12412033,  0.04439559,
       -0.09563146, -0.09804222, -0.12355245, -0.08760766, -0.05508853,
       -0.11185899, -0.21370353, -0.15625048,  0.01922055, -0.0075576 ,
       -0.08421326, -0.09371297, -0.11334338, -0.00218866,  0.15678103,
       -0.00675758, -0.17844066, -0.03577978, -0.15900594,  0.17603944,
        0.20518072, -0.00151498, -0.04075604,  0.06392112, -0.06193347,
        0.01843332, -0.12607597,  0.11430847, -0.05522741,  0.03

In [23]:
np.dot(model['paul_gauguin'], model['paul_gauguin'])

1.0000000474728836

In [18]:
model.get_vector('paul_gauguin')

array([-0.08629142,  0.07500088,  0.11760277, -0.08249155, -0.06064167,
        0.07426202,  0.09430011,  0.03980861, -0.08868426, -0.07577797,
       -0.0789656 ,  0.04316986, -0.03742662,  0.0179255 , -0.02202932,
       -0.14584379, -0.0812774 ,  0.0817908 , -0.11009061, -0.07277608,
        0.02505444, -0.16708674,  0.09783117, -0.09566039,  0.20745072,
       -0.0382571 ,  0.03811841, -0.07231975, -0.25124985, -0.00223061,
       -0.15504658,  0.00175373, -0.0425612 ,  0.01211503, -0.21824302,
       -0.08570092, -0.11000088,  0.08192769,  0.12412033,  0.04439559,
       -0.09563146, -0.09804222, -0.12355245, -0.08760766, -0.05508853,
       -0.11185899, -0.21370353, -0.15625048,  0.01922055, -0.0075576 ,
       -0.08421326, -0.09371297, -0.11334338, -0.00218866,  0.15678103,
       -0.00675758, -0.17844066, -0.03577978, -0.15900594,  0.17603944,
        0.20518072, -0.00151498, -0.04075604,  0.06392112, -0.06193347,
        0.01843332, -0.12607597,  0.11430847, -0.05522741,  0.03

In [24]:
model.vocab.tolist()

['</s>',
 'pablo_picasso',
 'henri_matisse',
 'paul_klee',
 'jasper_johns',
 'ben_shahn',
 'max_ernst',
 'robert_rauschenberg',
 'georges_braque',
 'charles_sheeler',
 'marc_chagall',
 'ernst_ludwig_kirchner',
 'jim_dine',
 'odilon_redon',
 'georges_rouault',
 'alberto_giacometti',
 'otto_dix',
 'amedeo_modigliani',
 'pavel_tchelitchew',
 'claes_oldenburg',
 'george_grosz',
 'vasily_kandinsky',
 'henry_moore',
 'juan_gris',
 'fernand_l�ger',
 'lyonel_feininger',
 'jean_(hans)_arp',
 'pierre_bonnard',
 'robert_motherwell',
 'max_beckmann',
 'constantin_brancusi',
 'piet_mondrian',
 'sol_lewitt',
 'alexander_calder',
 'joan_mir�',
 'kurt_schwitters',
 'john_marin',
 'hilaire-germain-edgar_degas',
 'jacques_lipchitz',
 'jules_pascin',
 'lovis_corinth',
 'giorgio_de_chirico',
 'stuart_davis',
 'paul_c�zanne',
 'umberto_boccioni',
 'pierre-auguste_renoir',
 'man_ray',
 'alfred_stieglitz',
 'jacques_villon',
 'jean_dubuffet',
 'emil_nolde',
 'marcel_duchamp',
 'oskar_kokoschka',
 'edward_ste

In [29]:
model.distance('john_cage', 'garry_winogrand', 'vija_celmins', 'r._buckminster_fuller')

[('paul_gauguin', 'garry_winogrand', -0.15241404898190392),
 ('paul_gauguin', 'vija_celmins', 0.06587801112041479),
 ('paul_gauguin', 'r._buckminster_fuller', 0.10116291974532937),
 ('garry_winogrand', 'vija_celmins', 0.02747364087757806),
 ('garry_winogrand', 'r._buckminster_fuller', -0.1387934514854257),
 ('vija_celmins', 'r._buckminster_fuller', -0.18394813610642752)]

In [3]:
i, m = model.similar('john_cage')
model.generate_response(i, m).tolist()

[('art_&_language', 0.6979109085805235),
 ('fred_sandback', 0.652470928871357),
 ('mark_di_suvero', 0.6413962847506356),
 ('larry_poons', 0.6350292764581003),
 ('dan_flavin', 0.6283743217440056),
 ('mel_bochner', 0.6206653480549449),
 ('�yvind_fahlstr�m', 0.6113966768420281),
 ('chuck_close', 0.6089421353703656),
 ('james_lee_byars', 0.6063705641385664),
 ('lawrence_weiner', 0.6000357451473296)]

In [33]:
i, m = model.similar('vija_celmins')
model.generate_response(i, m).tolist()

[('gerald_ferguson', 0.6222738443372398),
 ('tom_holland', 0.5875425137680775),
 ('friedrich_meckseper', 0.587264051128488),
 ('m._c._escher', 0.5797073417044912),
 ('philippe_mohlitz', 0.5667956782562765),
 ('don_nice', 0.5543624275945845),
 ('wayne_thiebaud', 0.5340644921487281),
 ('georg_scholz', 0.4980920044838685),
 ('jos�-guadalupe_posada', 0.4870062988012811),
 ('edward_ruscha', 0.47189296487389004)]

In [28]:
model.distance('vincent_van_gogh', 'r._buckminster_fuller')

[('vincent_van_gogh', 'r._buckminster_fuller', 0.085627704904055)]

In [13]:
indices, metrics = model.similar('pablo_picasso', 'amedeo_modigliani')

NameError: name 'model' is not defined

In [30]:
model.generate_response(indices, metrics).tolist()

[('amedeo_modigliani', 0.568680260248791),
 ('jules_pascin', 0.517871728756046),
 ('pavel_tchelitchew', 0.5157905151811865),
 ('georges_rouault', 0.46760121022004514),
 ('georges_braque', 0.4603618889284767),
 ('paul_klee', 0.4525742209762877),
 ('henri_matisse', 0.44027685073796274),
 ('rufino_tamayo', 0.4217588619041713),
 ('odilon_redon', 0.42165499166817566),
 ('kurt_schwitters', 0.4042661275156295)]

In [3]:
clusters = word2vec.load_clusters('../word2vec_output_clusters-2.txt')

In [4]:
clusters.vocab

array(['</s>', 'W', 'w', 'j'], dtype='<U4')

In [12]:
clusters.get_words_on_cluster(2)

array(['W'], dtype='<U4')